open-ai:
  url: "https://api.openai.com/v1/"
  api-key: "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"
papago:
  url: "https://openapi.naver.com/v1/papago/n2mt"
  client-id: "gg0TWNVLDhSEzTpBAUpN"
  client-secret: "XNpCBv6WLH"
slack:
  url: "https://openapi.naver.com/v1/papago"
  client-id: "gg0TWNVLDhSEzTpBAUpN"
  client-secret: "XNpCBv6WLH"
